### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by LaurentBEDIEF** [FMudanyali/freeglut-vita#1]
hi,

i have a compilation error : 

lolo@LAPTOP-9VORJ90G MSYS ~/freeglut-vita/build
$ cmake .. -DVITA=1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lolo/freeglut-vita/build

lolo@LAPTOP-9VORJ90G MSYS ~/freeglut-vita/build
$ make
[  2%] Building C object CMakeFiles/freeglut_static.dir/src/fg_callbacks.c.obj
[  4%] Building C object CMakeFiles/freeglut_static.dir/src/fg_cursor.c.obj
[  7%] Building C object CMakeFiles/freeglut_static.dir/src/fg_display.c.obj
[  9%] Building C object CMakeFiles/freeglut_static.dir/src/fg_ext.c.obj
[ 12%] Building C object CMakeFiles/freeglut_static.dir/src/fg_font_data.c.obj
[ 14%] Building C object CMakeFiles/freeglut_static.dir/src/fg_gamemode.c.obj
[ 17%] Building C object CMakeFiles/freeglut_static.dir/src/fg_geometry.c.obj
[ 19%] Building C object CMakeFiles/freeglut_static.dir/src/fg_gl2.c.obj
[ 21%] Building C object CMakeFiles/freeglut_static.dir/src/fg_init.c.obj
[ 24%] Building C object CMakeFiles/freeglut_static.dir/src/fg_input_devices.c.obj
[ 26%] Building C object CMakeFiles/freeglut_static.dir/src/fg_joystick.c.obj
[ 29%] Building C object CMakeFiles/freeglut_static.dir/src/fg_main.c.obj
[ 31%] Building C object CMakeFiles/freeglut_static.dir/src/fg_misc.c.obj
[ 34%] Building C object CMakeFiles/freeglut_static.dir/src/fg_overlay.c.obj
[ 36%] Building C object CMakeFiles/freeglut_static.dir/src/fg_spaceball.c.obj
[ 39%] Building C object CMakeFiles/freeglut_static.dir/src/fg_state.c.obj
[ 41%] Building C object CMakeFiles/freeglut_static.dir/src/fg_stroke_mono_roman.c.obj
[ 43%] Building C object CMakeFiles/freeglut_static.dir/src/fg_stroke_roman.c.obj
[ 46%] Building C object CMakeFiles/freeglut_static.dir/src/fg_structure.c.obj
[ 48%] Building C object CMakeFiles/freeglut_static.dir/src/fg_teapot.c.obj
[ 51%] Building C object CMakeFiles/freeglut_static.dir/src/fg_videoresize.c.obj
[ 53%] Building C object CMakeFiles/freeglut_static.dir/src/fg_window.c.obj
[ 56%] Building C object CMakeFiles/freeglut_static.dir/src/gles_stubs.c.obj
[ 58%] Building C object CMakeFiles/freeglut_static.dir/src/android/fg_cursor_android.c.obj
[ 60%] Building C object CMakeFiles/freeglut_static.dir/src/android/fg_ext_android.c.obj
[ 63%] Building C object CMakeFiles/freeglut_static.dir/src/android/fg_gamemode_android.c.obj
[ 65%] Building C object CMakeFiles/freeglut_static.dir/src/android/fg_joystick_android.c.obj
[ 68%] Building C object CMakeFiles/freeglut_static.dir/src/android/fg_spaceball_android.c.obj
[ 70%] Building C object CMakeFiles/freeglut_static.dir/src/vita/fg_init_vita.c.obj
[ 73%] Building C object CMakeFiles/freeglut_static.dir/src/vita/fg_input_vita.c.obj
[ 75%] Building C object CMakeFiles/freeglut_static.dir/src/vita/fg_main_vita.c.obj
E:/DolceSdk/home/lolo/freeglut-vita/src/vita/fg_main_vita.c: In function 'fgPlatformProcessSingleEvent':
E:/DolceSdk/home/lolo/freeglut-vita/src/vita/fg_main_vita.c:67:47: warning: comparison between pointer and integer
   67 |   if (window != NULL && window->Window.Handle != NULL) {
      |                                               ^~
[ 78%] Building C object CMakeFiles/freeglut_static.dir/src/vita/fg_state_vita.c.obj
[ 80%] Building C object CMakeFiles/freeglut_static.dir/src/vita/fg_window_vita.c.obj
E:/DolceSdk/home/lolo/freeglut-vita/src/vita/fg_window_vita.c: In function 'fgPlatformOpenWindow':
E:/DolceSdk/home/lolo/freeglut-vita/src/vita/fg_window_vita.c:32:47: warning: comparison between pointer and integer
   32 |   if (fgDisplay.pDisplay.single_native_window != NULL) {
      |                                               ^~
E:/DolceSdk/home/lolo/freeglut-vita/src/vita/fg_window_vita.c:36:45: error: incompatible types when assigning to type 'EGLNativeWindowType' {aka 'enum VitaEGLNativeWindow'} from type 'SFG_Window *' {aka 'struct tagSFG_Window *'}
   36 |   fgDisplay.pDisplay.single_native_window = window;
      |                                             ^~~~~~
make[2]: *** [CMakeFiles/freeglut_static.dir/build.make:498: CMakeFiles/freeglut_static.dir/src/vita/fg_window_vita.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/freeglut_static.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

lolo@LAPTOP-9VORJ90G MSYS ~/freeglut-vita/build

 could you help me ?

thanks

**Comment by FMudanyali** [comment]
Can you try it now? I pushed a fix. Don't forget to run cmake again

**Comment by LaurentBEDIEF** [comment]
thank you ;-)   it compile .
